### ISSUE TITLE
Images are not visible in Dark Mode

### ISSUE THREAD

**Issue by rwiteshbera** [InterviewReady/joy-of-system-design#3]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/73098407/212526061-51478672-c84f-4c5a-b911-1d712896dceb.png">

**Comment by coding-parrot** [comment]
Hi @rwiteshbera , the image is a transparent one and a low-fidelity image. We are yet to decide on the final design.

Do you mean the image is not visible in dark mode README file?

**Comment by rwiteshbera** [comment]
yes, the images are not properly visible as I am using dark mode.
